<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: secubian
 * Date: Fri, 31 Jan 2020 06:39:48 -0600
 */

$conf['title'] = 'Secubian';
$conf['lang'] = 'fr';
$conf['template'] = 'sprintdoc';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;
$conf['tpl']['sprintdoc']['header_layout'] = 'header-compact';

// end auto-generated content
